import { Footer, Header, ImageModal, Sidebar } from "./components";
import "./globals.css";
import { Kumbh_Sans } from "next/font/google";

const Kumbh = Kumbh_Sans({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Frontend Mentor | E-commerce product page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Kumbh.className}>
        <div className="w-screen min-h-screen relative bg-white flex flex-col">
          <ImageModal />
          <Sidebar />
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
